import type { Metadata } from "next";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import "./globals.css";
import { ThemeProvider } from "../context/ThemeContext";
import { HeaderSearch } from "@/components/Header";
import { FooterLinks } from "@/components/Footer";
import { cookies } from "next/headers";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <ThemeProvider>
          <MantineProvider>
            <HeaderSearch />
            <main>{children}</main>
            <FooterLinks />
          </MantineProvider>
        </ThemeProvider>
        <ToastContainer
          position="bottom-right"
          autoClose={3000}
          limit={5}
          hideProgressBar={false}
          newestOnTop
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable={false}
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  );
}
